let listaDosFatos = [
    {ano: 1920, frases: "Início da década de 1920, marcada pelo pós-Primeira Guerra Mundial."},
    {ano: 1921, frases: "Fundação do Partido Comunista Chinês."},
    {ano: 1922, frases: "Semana de Arte Moderna acontece no Brasil."},
    {ano: 1923, frases: "Fundação da Disney por Walt Disney e Roy O. Disney."},
    {ano: 1924, frases: "Lenin morre e Stalin começa a consolidar seu poder na União Soviética."},
    {ano: 1925, frases: "Publicação de 'Mein Kampf' por Adolf Hitler."},
    {ano: 1926, frases: "Primeira transmissão pública de televisão ocorre no Reino Unido."},
    {ano: 1927, frases: "Lançamento do primeiro filme falado, 'O Cantor de Jazz'."},
    {ano: 1928, frases: "Alexander Fleming descobre a penicilina."},
    {ano: 1929, frases: "Quebra da Bolsa de Nova York e início da Grande Depressão."},
    {ano: 1930, frases: "Getúlio Vargas assume o poder no Brasil."},
    {ano: 1931, frases: "O Empire State Building é inaugurado."},
    {ano: 1932, frases: "Mulheres conquistam o direito ao voto no Brasil."},
    {ano: 1933, frases: "Hitler se torna chanceler da Alemanha."},
    {ano: 1934, frases: "Morte do presidente brasileiro Getúlio Vargas e início do Estado Novo."},
    {ano: 1935, frases: "Lançamento do primeiro livro da série 'O Senhor dos Anéis', de J.R.R. Tolkien."},
    {ano: 1936, frases: "Início da Guerra Civil Espanhola."},
    {ano: 1937, frases: "Lançamento do filme 'Branca de Neve e os Sete Anões'."},
    {ano: 1938, frases: "A Alemanha anexa a Áustria na Anschluss."},
    {ano: 1939, frases: "Início da Segunda Guerra Mundial com a invasão da Polônia."},
    {ano: 1940, frases: "Winston Churchill se torna primeiro-ministro do Reino Unido."},
    {ano: 1941, frases: "Ataque a Pearl Harbor e entrada dos EUA na Segunda Guerra Mundial."},
    {ano: 1942, frases: "Lançamento do filme 'Casablanca'."},
    {ano: 1943, frases: "Conferência de Teerã define estratégias para o fim da guerra."},
    {ano: 1944, frases: "Desembarque do Dia D na Normandia."},
    {ano: 1945, frases: "Fim da Segunda Guerra Mundial."},
    {ano: 1946, frases: "Criação da ONU."},
    {ano: 1947, frases: "Independência da Índia do domínio britânico."},
    {ano: 1948, frases: "Criação do Estado de Israel."},
    {ano: 1949, frases: "Fundação da OTAN."},
    {ano: 1950, frases: "Início da Guerra da Coreia."},
    {ano: 1951, frases: "Primeiro computador comercial é lançado."},
    {ano: 1952, frases: "Elizabeth II se torna rainha do Reino Unido."},
    {ano: 1953, frases: "Morte de Stalin e ascensão de Khrushchev."},
    {ano: 1954, frases: "Guerra do Vietnã começa a se intensificar."},
    {ano: 1955, frases: "Fundação da Disney World."},
    {ano: 1956, frases: "Independência do Sudão."},
    {ano: 1957, frases: "Lançamento do Sputnik, primeiro satélite artificial."},
    {ano: 1958, frases: "Fundação da NASA."},
    {ano: 1959, frases: "Revolução Cubana liderada por Fidel Castro."},
    {ano: 1960, frases: "Início dos movimentos pelos direitos civis nos EUA."},
    {ano: 1961, frases: "Primeiro voo tripulado ao espaço com Yuri Gagarin."},
    {ano: 1962, frases: "Crise dos Mísseis de Cuba."},
    {ano: 1963, frases: "Assassinato do presidente John F. Kennedy."},
    {ano: 1964, frases: "Golpe militar no Brasil."},
    {ano: 1965, frases: "Primeiro grande protesto contra a Guerra do Vietnã nos EUA."},
    {ano: 1966, frases: "Lançamento da série de TV Star Trek."},
    {ano: 1967, frases: "Primeiro transplante de coração realizado por Dr. Christiaan Barnard."},
    {ano: 1968, frases: "Assassinato de Martin Luther King Jr."},
    {ano: 1969, frases: "O homem pisa na Lua pela primeira vez."},
    {ano: 1970, frases: "Criação da Petrobras."},
    {ano: 1971, frases: "Lançamento do microprocessador Intel 4004."},
    {ano: 1972, frases: "Jogos Olímpicos de Munique marcados por ataques terroristas."},
    {ano: 1973, frases: "Crise do petróleo impacta o mundo."},
    {ano: 1974, frases: "Renúncia do presidente dos EUA, Richard Nixon, após o escândalo Watergate."},
    {ano: 1975, frases: "Fim da Guerra do Vietnã."},
    {ano: 1980, frases: "Assassinato de John Lennon."},
    {ano: 1989, frases: "Queda do Muro de Berlim."},
    {ano: 1991, frases: "Fim da União Soviética."},
    {ano: 2001, frases: "Ataques de 11 de setembro nos EUA."},
    {ano: 2008, frases: "Crise financeira global."},
    {ano: 2010, frases: "Início da Primavera Árabe."},
    {ano: 2016, frases: "Impeachment de Dilma Rousseff no Brasil."},
    {ano: 2020, frases: "Pandemia da COVID-19 se espalha pelo mundo."}
  ]
  
exports.lista = listaDosFatos